### ISSUE TITLE
selenoid in docker won't start correctly if run with --args

### ISSUE THREAD

**Issue by ksiv** [aerokube/cm#112]
I installed selenoid 1.4.1 via cm 1.3.1
Ubuntu 16.04 LTS 64bit 4.4.0-103-generic
The issue is-  launched with --args "-session-attempt-timeout=1m0s" or -g "-session-attempt-timeout 1m0s" or --args "-session-attempt-timeout 1m0s", same for --args "-limit 5".
the container remains in state Restarting or Exiting (more common the former).
how do I pass these params correctly? 
cm always reports Successfully started selenoid but "docker ps -a" shows it in wrong state and inspection shows that it has no IP address.

starting only with -c and --vnc flags works ok

**Comment by vania-pooh** [comment]
@ksiv it current release it requires `-conf` to be passed when specifying `--args`. This was fixed in #110 and should not reproduce with `aerokube/cm:latest` container. Please check whether it works for you.

**Comment by ksiv** [comment]
@vania-pooh, thanks a lot. I ll try docker version of cm. I used standalone version of cm before.

**Comment by vania-pooh** [comment]
@ksiv this is just the same binary. The difference is that we automatically push updated container image on any master changes and don't do that for binaries.

**Comment by ksiv** [comment]
@vania-pooh, I tried executable container version. It works in different way by executing standalones inside one container and I did not figured out how to manage the process.  I made a playbook it executes start for selenoid and selenoid-ui as well as stop. We planning to keep browsers.json in git. and we use "jq" to parse browsers.json as described in docs. We will wait  for standalone cm executable, i think.

**Comment by vania-pooh** [comment]
@ksiv euh, running the following command:
```
docker run --rm                                   \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    -v ${HOME}:/root                                \
    -e OVERRIDE_HOME=${HOME}                        \
    aerokube/cm:latest selenoid start       \
    --vnc --tmpfs 128 --args "-limit 10"
```
... should deliver just the same thing as running the binary (no release yet):
```
$ ./cm selenoid start --vnc --tmpfs 128 --args "-limit 10"
```
I can compile a binary for your from source to try.

**Comment by ksiv** [comment]
no need for compiling it's easy to get from container.
I tried this script it worked but it won't load my custom config if I add -c /opt/selenoid/. 
I can see it loads opera images that I removed and in "docker logs" I can see it reads config from /etc/selenoid/

**Comment by ksiv** [comment]
Tried several more times. this command works but I can not add there "-c" option to run my custom config.
 The selenoid always starts with config from "/etc/selenoid".
if I add to this command "-c test" - it will create a test folder in the home which is expected somehow and places there a browser.json. but if I edit this file and restart selenoid with the same command line it won't read it. I check it via "docker logs" and the "status" page. The file reminds intact after restart but it's not used.

**Comment by vania-pooh** [comment]
@ksiv ok, let us just release this fix and you will try. :)

**Comment by ksiv** [comment]
I tried with binary from latest image it with same result. (ldd says it's non dynamic but it may be mistaken)
sudo cm2 selenoid start -c /opt/selenoid/config --vnc 
will start selenoid with my config.
sudo cm2 selenoid start -c  /opt/selenoid/config --vnc --args "limit 2"
won't start selenoid, the container remains in restarting state 
docker logs reports:
/usr/bin/selenoid: browsers config : read error: open config/browsers.json: no such file or dirrectory.

md5 4251bec45ad4b8c0fbb6ec0c908dcc1e  ./cm2
extracted from aerokube/cm:latest dated Dec 13 11:50 
stat size 12491899

**Comment by lanwen** [comment]
Please try `v1.3.2` (released a hour ago)

**Comment by ksiv** [comment]
the same behavior for me.

**Comment by lanwen** [comment]
Please copy your exact command

**Comment by ksiv** [comment]
Sorry my bad, took wrong command from history with "limit 5" instead of "-limit 5"
Now new cm works. the container is up and running.
Thanks a lot

**Comment by vania-pooh** [comment]
Closing?

**Comment by ksiv** [comment]
Sure

**Comment by vania-pooh** [comment]
:)
