### ISSUE TITLE
Not able to start selenoid server on windows 64 bit machine

### ISSUE THREAD

**Issue by sjethvani** [aerokube/cm#124]
As a starter , I am following up wiki mentioned [here](http://aerokube.com/selenoid/latest/) to run selenoid without docker on windows & accordingly downloaded cm*.exe file . 
Now when I tried to start selenoid , it downloaded required binaries & afterwards tried starting selenium server . Here it is giving me error msg like  'The requested service provider could not be loaded or initialized'

Attaching snap showing commands i tried . I tried chaging ports assuming port conflict issues , however it didnt help me . Can you help me stating what I am doing wrong 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/3015677/34566325-1ccccbbe-f184-11e7-8641-f01bcd7565a3.png">

**Comment by vania-pooh** [comment]
@sjethvani sometimes Windows security settings prevent Selenoid process from starting. To fix this issue you should start in manually using the following command:
```
> C:\Users\jgoda\.aerokube\selenoid\selenoid_windows_amd64.exe -conf C:\Users\jgoda\.aerokube\selenoid\browsers.json -disable-docker -listen :4445
```
The last flag (`-listen`) is optional and defines service port. We are currently not sure how to prevent Windows from blocking such processes. Related StackOveflow question: https://stackoverflow.com/questions/33072364/socket-10106-error-node

**Comment by sjethvani** [comment]
I am able to start hub by your above direct command
`C:\Users\jgoda\.aerokube\selenoid\selenoid_windows_amd64.exe -conf C:\Users\jgoda\.aerokube\selenoid\browsers.json -disable-docker -listen :4445
` 

I followed same approach to start selenoid-ui using following kinda direct command
<img width="679" alt="image" src="https://user-images.githubusercontent.com/3015677/34598051-8bde5cac-f210-11e7-9090-36077d1090d9.png">

On browser it shows as follows , however it doesn't show any browsers in drop down list . 
**Question 1** : (Not able to see browsers mentioned in browser.config file)
Will it be shown when I execute my actual selenium test ? 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/3015677/34598079-bd40a2f0-f210-11e7-8bef-5ed600bf5898.png">

browser.config 
`    "chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": [
                    "C:\\Users\\jgoda\\.aerokube\\selenoid\\chromedriver.exe",
                    "--whitelisted-ips=''",
                    "--verbose"
                ],
                "port": "4445",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": [
                    "C:\\Users\\jgoda\\.aerokube\\selenoid\\geckodriver.exe",
                    "--host",
                    "::",
                    "--log",
                    "debug"
                ],
                "port": "4445",
                "path": "/wd/hub"
            }
        }
    }`

Note : Here it shows that if i want to execute selenium tests on selenoid then i should point RemoteWebdriver to url like 'http://selenoid-uri:4444/wd/hub' . Now since I am starting selenoid on port '4445' , I navigated to url ('http://selenoid-uri:4444/wd/hub') , however it gives me DNS error (as shown below)
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/3015677/34598220-630ccd12-f211-11e7-920a-fbfdf73a39c6.png">
however when accessing this url 

More details 
selenoid hub status is shown as json response (below snap) 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3015677/34598091-cded071a-f210-11e7-8aa4-b5e5825071fd.png">

**Question 2** (Not able to start vnc on selenoid)
I tried enabling 'vnc' while starting selenoid using following command 
`C:\Users\jgoda\.aerokube\selenoid\selenoid_windows_amd64.exe -conf C:\Users\jgoda\.aerokube\selenoid\browsers.json -disable-docker -vnc -listen :4445`
however this says '-vnc' not defined .
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3015677/34598358-45f83b8e-f212-11e7-9688-7a196d94ca14.png">

**Comment by vania-pooh** [comment]
1) So far as you are using non-standard Selenoid port you should tell it to Selenoid UI:
```
> C:\Users\jgoda\.aerokube\selenoid\selenoid-ui_windows_amd64.exe --selenoid-uri http://localhost:4445/
```
2) VNC feature makes sense only with Docker because without it you can see browser screen directly. To work with this feature you need to use browser images with `vnc` in name (e.g. `selenoid/vnc:firefox_46.0`) and add `enableVNC` capability to your tests. No need to add flags to Selenoid startup command. When adding `--vnc` flag to CM utility you tell it to download VNC browser images instead of ordinary images.

3) In your case you should use the following Selenium URL in tests: `http://localhost:4445/wd/hub`. We are using `selenoid-uri` as a placeholder. Sorry if that's confusing.

**Comment by sjethvani** [comment]
Thanks for reply . 
I was able to figure out the 1st one . I searched your wiki and found this '--selenoid-uri' flag & added it accordingly when starting selenoid-ui. 
Now I am able to see browsers (mentioned in .config file) by accessing url 
http://localhost:8080 

Regarding 2nd question 
The reason I am interested to use VNC without docker is (A. I am using windows and docker is not that much compatible with windows B. I want to let my other team members see whats happening with their tests (live execution) without giving them RDP access of node machine.

**Comment by vania-pooh** [comment]
@sjethvani I would say currently Docker is much more mature than it was previously. With Windows 10 you can run Docker using built-in Hyper-V Windows virtualization - that is to say, without VirtualBox. We are mainly focusing on Docker-related features because Selenoid was initially created to be run on headless server as a part of big Selenium clusters. So you could just install it on Linux hardware server or virtual machine in some cloud platform and everybody will have access to running tests, VNC and video recording.

**Comment by sjethvani** [comment]
I see 
I will surely try with docker on windows 10 machine . 

But for now provided that I am having some old windows 2008 ec2 servers (provided by my office) selenoid won't be able to provide vnc without docker environment ? I would be able to vnc my browser execution only with vnc enabled docker images . Isn't it ?. 

Thanks for reply :)

**Comment by vania-pooh** [comment]
Currently VNC feature just does not work without Docker.

**Comment by sjethvani** [comment]
Thanks for reply . Well I am closing this issue as my basic aim of running selenoid without docker is resolved . Thanks for clarification @vania-pooh
