### ISSUE TITLE
Firefox browser.conf issue (Win 10)

### ISSUE THREAD

**Issue by gototester** [aerokube/cm#141]
When using the default config on windows 10, Firefox does not launch. 

Default: 
    "firefox": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": [
                    "C:/Users/Test User/.aerokube/selenoid/geckodriver.exe",
                    "--host",
                    "::",
                    "--log",
                    "debug"
                ],
                "port": "",
                "path": "/"
            }
        }
    }

    It works when I change it too:

    "firefox": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": [
                    "C:/Users/Test User/.aerokube/selenoid/geckodriver.exe",
                    "--host=127.0.0.1",
                    "--log",
                    "debug"
                ],
                "port": "",
                "path": "/"
            }
        }
    }

**Comment by vania-pooh** [comment]
Hmm, do you have IPv6 adapter enabled?

**Comment by gototester** [comment]
checked my network adaptor setting and IPv6 is not enabled only IPv4.

**Comment by vania-pooh** [comment]
Ok, will consider how to fix this. `::` means listen on IPv6 adapter.
