### ISSUE TITLE
Add ability to download only specified browser versions

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/cm#155]
Something like: `./cm selenoid start --browsers chrome=65.0,firefox=57.0`. Also support semver expressions like: https://github.com/blang/semver

**Comment by KathiresanRamkumar95** [comment]
But, Using docker How do I specify my browsers.json conf file to start Selenoid using Configuration Manager?
Please Help me to get my need.
@vania-pooh

**Comment by KathiresanRamkumar95** [comment]
Even After the host machine directory mounted with runner selenoid container. Still, I get firefox and opera in selenoid UI instead of chrome.(Note: chrome details updated with browsers.json file in the path of /etc/selenoid.browsers.json)

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 specifying you own `browsers.json` is not supported. You only can do the following: https://aerokube.com/selenoid/latest/#_syncing_browser_images_from_existing_file
