### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by MissiaL** [aerokube/cm#17]
Do you have PhantomJS support?

**Comment by vania-pooh** [comment]
Yes. There's `selenoid/phantomjs:2.1.1` image. But so far as Phantomjs author deprecated the project we did not include automatic phantomjs installation to cm. You may want to add respective entry and pull the image manually. Did it help?

**Comment by vania-pooh** [comment]
@MissiaL any updates?

**Comment by MissiaL** [comment]
@vania-pooh Thanks for help)
