### ISSUE TITLE
ubuntu16.0.4 cannot cm download vnc

### ISSUE THREAD

**Issue by kiam123** [aerokube/cm#173]
hi , i type this command will stop in 2018/07/18 21:59:45 [-] [INIT] [Listening on :4444] , how can fix this problem ?
$ curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc
![image](https://user-images.githubusercontent.com/14953180/42886405-14173bda-8ad6-11e8-8a1f-6d31672b277e.png)
![image](https://user-images.githubusercontent.com/14953180/42886443-27181be6-8ad6-11e8-9ab9-88f5637d4dde.png)

**Comment by kiam123** [comment]
ok, thanks your reply. If I ask some stupid questions, please be more tolerant, because I am a newcomer to Linux. Tomorrow i try it.

**Comment by kiam123** [comment]
Docker has been installed, with the addition of the "sudo" command, but still show "Docker is not supported - using binaries..."
![image](https://user-images.githubusercontent.com/14953180/42937737-7b2386d8-8b82-11e8-8eeb-89a9bfb28579.png)
![image](https://user-images.githubusercontent.com/14953180/42937947-31a20b5a-8b83-11e8-837e-72da6dcffea8.png)
![image](https://user-images.githubusercontent.com/14953180/42937972-556325f6-8b83-11e8-96d6-b111e9b0155f.png)

**Comment by vania-pooh** [comment]
@kiam123 then `docker ps` command will also not work.

**Comment by kiam123** [comment]
![image](https://user-images.githubusercontent.com/14953180/42938937-a010969e-8b86-11e8-9847-372262687ee7.png)

**Comment by vania-pooh** [comment]
@kiam123 yes, works with `sudo` and will not without it. But cm is launched without `sudo` in your command, only `curl` is being run with sudo. Possible solutions:
1) `sudo sh -c "curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc"`
2) Add your user to `docker` group:
```
sudo usermod -a -G docker $(whoami)
```

**Comment by kiam123** [comment]
@vania-pooh thank you, problem solved

**Comment by vania-pooh** [comment]
Closing then. :)
