### ISSUE TITLE
Userns-remap

### ISSUE THREAD

**Issue by MitRandi** [aerokube/cm#178]
It will be great to find a way to run selenoid container with additional docker parameters. 
For the most for me it is "--userns=host " to allow solenoid container to bypass users-remap restrictions.

**Comment by vania-pooh** [comment]
@MitRandi probably we need to move this issue to Selenoid repository then.

**Comment by MitRandi** [comment]
Hi @vania-pooh, thanks for reply, https://github.com/aerokube/selenoid/issues/503
