### ISSUE TITLE
Flag to turn off saving logs in Selenoid

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/cm#197]
Otherwise it clutters disk space.

**Comment by jsa34** [comment]
Fab!  Thank you for this!

**Comment by vania-pooh** [comment]
@jsa34 could you try whether an attached binary works for you? Command would be:
```
$ ./cm selenoid start --disable-logs <..rest of the args>
```
[cm.zip](https://github.com/aerokube/cm/files/2528033/cm.zip)

**Comment by jsa34** [comment]
Just running now with suggested binary and no logs produced 👍   

Thanks @vania-pooh !

**Comment by jsa34** [comment]
Fixed in cm :)

Closed

(Thanks @vania-pooh!)

**Comment by snackattas** [comment]
@vania-pooh is there a way to pass this option `--disable-logs` in the compose file?

**Comment by vania-pooh** [comment]
@snackattas yep, there is `command` section: https://docs.docker.com/compose/compose-file/#command
