### ISSUE TITLE
Can't start/stop solenoid when docker registry unavailable 

### ISSUE THREAD

**Issue by biomaks** [aerokube/cm#199]
Today I ran into the issue that I can't stop solenoid containers using `cm` tool. I definitely can use docker commands directly, but it seems wrong to me that I can't do anything with `cm` if docker registry  is unavailable. Even `cm solenoid args` didn't work. I have no idea why to ping docker registry on each command.

    ./cm selenoid stop
    > Using Docker
    - Your Docker API version is 1.37
    registry.ping url=https://registry.hub.docker.com/v2/
    Failed to initialize: [new configurator: Docker Registry is not available: Get https://registry.hub.docker.com/v2/: http: non-successful response (status=401 body="{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":null}]}\n")]```

**Comment by vania-pooh** [comment]
@biomaks ok, will see what can be done with it.
