### ISSUE TITLE
"cm selenoid start" doesn't add tmpfs volume

### ISSUE THREAD

**Issue by mopul** [aerokube/cm#212]
CM version: 1.5.7

```
root@localhost:~/.aerokube/selenoid# cm selenoid start --tmpfs 256 --args "-enable-file-upload"
> Using Docker
- Your Docker API version is 1.39
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid
root@localhost:~/.aerokube/selenoid# docker volume ls
DRIVER              VOLUME NAME
root@localhost:~/.aerokube/selenoid#
```

Finally it causes that file uploading fails with error message: `org.openqa.selenium.WebDriverException: invalid argument: File not found : /tmp/2415d58faed24d61aafc6c4ab4fb15a9/filename.csv`

**Comment by vania-pooh** [comment]
@mopul 
1) First of all `-enable-file-upload` flag is not needed when using Selenoid with Docker. Just remove it and file upload will work.
2) `--tmpfs` flag should add respective entry to generated `browsers.json`. If it does it - then this feature works.
