### ISSUE TITLE
Failed to start: Selenoid image is not downloaded: this is probably a bug - windows 10 on VM

### ISSUE THREAD

**Issue by etuviana** [aerokube/cm#218]
Hi i type this command **./cm selenoid start** ,but i get
"Failed to start: Selenoid image is not downloaded: this is probably a bug "
i try also -  **./cm selenoid start --vnc --force**
but same Error massage
https://prnt.sc/mzuw38

Host:- VM
OS :- MS Windows 10 
H/W:- CPU: 4, Memory: 16GB, HD: 200 GB

please Help me :)

**Comment by vania-pooh** [comment]
@etuviana you have to switch Docker to Linux mode. This can be done in GUI. https://www.containerstack.io/docker-on-windows-switch-to-windows-linux-mode/

**Comment by etuviana** [comment]
@vania-pooh  Successfully started Selenoid UI
thanks a lot :)

**Comment by vania-pooh** [comment]
Closing then.
