### ISSUE TITLE
Ability to set shmsize through cm

### ISSUE THREAD

**Issue by jsa34** [aerokube/cm#222]
I might be missing how to do this from the documentation, but rather than use a json file to set the shmsize, could this be set through ./cm selenoid update?

It is the only command that would seemingly need to be set via the json for update scripts at the moment it appears...

**Comment by vania-pooh** [comment]
@jsa34 ok, will implementi t.

**Comment by jsa34** [comment]
Thanks, @vania-pooh...
I really appreciate how quick you are responding to issues!
