### ISSUE TITLE
cm don`t use registry-mirrors when using --force

### ISSUE THREAD

**Issue by patsevanton** [aerokube/cm#235]
cm_linux_amd64 selenoid start --vnc --force
> Using Docker
- Your Docker API version is 1.39
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
x Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp 34.199.66.136:443: i/o timeout
x Docker registry client not initialized
- Pulling image aerokube/selenoid
> Configuring Selenoid...
> Processing browser "opera"...
- Fetching tags for image selenoid/opera
registry.ping url=https://registry.hub.docker.com/v2/
x Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp 52.45.70.95:443: i/o timeout
x Docker registry client not initialized
- Requested to download VNC images...
> Processing browser "firefox"...
- Fetching tags for image selenoid/firefox
registry.ping url=https://registry.hub.docker.com/v2/
x Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp 34.199.66.136:443: i/o timeout
x Docker registry client not initialized
- Requested to download VNC images...
> Processing browser "chrome"...
- Fetching tags for image selenoid/chrome
registry.ping url=https://registry.hub.docker.com/v2/
x Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp 3.82.124.137:443: i/o timeout
x Docker registry client not initialized
- Requested to download VNC images...
> Pulling video recorder image...
- Pulling image selenoid/video-recorder:latest-release
> Configuration saved to /root/.aerokube/selenoid/browsers.json
> Starting Selenoid...
> Successfully started Selenoid

docker pull aerokube/selenoid
Using default tag: latest
latest: Pulling from aerokube/selenoid
Digest: sha256:7ad58196ca4f2fd442ad0b4a9e235c951eb43d430d01ca1d86d96acb4a64d9b0
Status: Image is up to date for aerokube/selenoid:latest

docker pull selenoid/opera
Using default tag: latest
latest: Pulling from selenoid/opera
Digest: sha256:c5d2a9f7c51fb9710d66f8e67defb28d6a339afd4c88c0b903c7ddc16b7c0fb0
Status: Downloaded newer image for selenoid/opera:latest

docker pull selenoid/firefox
Using default tag: latest
latest: Pulling from selenoid/firefox
Digest: sha256:000303296be77f8fcd760cea0030030a8e322f1fc11702638896b3305dd148d0
Status: Downloaded newer image for selenoid/firefox:latest

docker pull selenoid/chrome
Using default tag: latest
latest: Pulling from selenoid/chrome
Digest: sha256:007ceeb6740c70d747b64aaf2347544eeb9c4d734981af1a5d95ede44b0ff4fe
Status: Downloaded newer image for selenoid/chrome:latest

docker pull selenoid/video-recorder:latest-release
latest-release: Pulling from selenoid/video-recorder
Digest: sha256:72845bf9529b8716c14bd33a0a4b6919511bb9d60a821fe034938f69295cee5c
Status: Image is up to date for selenoid/video-recorder:latest-release

docker pull aerokube/selenoid
Using default tag: latest
latest: Pulling from aerokube/selenoid
Digest: sha256:7ad58196ca4f2fd442ad0b4a9e235c951eb43d430d01ca1d86d96acb4a64d9b0
Status: Image is up to date for aerokube/selenoid:latest

cm_linux_amd64 selenoid-ui stop
> Using Docker
- Your Docker API version is 1.39
> Selenoid UI is not running

cm_linux_amd64 selenoid start --vnc --force
> Using Docker
- Your Docker API version is 1.39
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
x Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp 34.199.66.136:443: i/o timeout
x Docker registry client not initialized
- Pulling image aerokube/selenoid
> Configuring Selenoid...
> Processing browser "firefox"...
- Fetching tags for image selenoid/firefox
registry.ping url=https://registry.hub.docker.com/v2/

   
cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://docker-registry.tools.myteam.ru:10443"]
}

**Comment by patsevanton** [comment]
cm_linux_amd64 selenoid start --vnc --force --registry https://docker-registry.tools.myteam.ru:10443

```
> Using Docker
- Your Docker API version is 1.39
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://docker-registry.tools.myteam.ru:10443/v2/
registry.tags url=https://docker-registry.tools.myteam.ru:10443/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image docker-registry.tools.myteam.ru/aerokube/selenoid:1.9.2
x Failed to pull image "docker-registry.tools.myteam.ru/aerokube/selenoid:1.9.2": Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>404 - Nexus Repository Manager</title>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n\n\n  <!--[if lt IE 9]>\n  <script>(new Image).src=\"https://docker-registry.tools.myteam.ru/favicon.ico?3.16.2-01\"</script>\n  <![endif]-->\n  <link rel=\"icon\" type=\"image/png\" href=\"https://docker-registry.tools.myteam.ru/favicon-32x32.png?3.16.2-01\" sizes=\"32x32\">\n  <link rel=\"mask-icon\" href=\"https://docker-registry.tools.myteam.ru/safari-pinned-tab.svg?3.16.2-01\" color=\"#5bbad5\">\n  <link rel=\"icon\" type=\"image/png\" href=\"https://docker-registry.tools.myteam.ru/favicon-16x16.png?3.16.2-01\" sizes=\"16x16\">\n  <link rel=\"shortcut icon\" href=\"https://docker-registry.tools.myteam.ru/favicon.ico?3.16.2-01\">\n  <meta name=\"msapplication-TileImage\" content=\"https://docker-registry.tools.myteam.ru/mstile-144x144.png?3.16.2-01\">\n  <meta name=\"msapplication-TileColor\" content=\"#00a300\">\n\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://docker-registry.tools.myteam.ru/static/css/nexus-content.css?3.16.2-01\"/>\n</head>\n<body>\n<div class=\"nexus-header\">\n  <a href=\"https://docker-registry.tools.myteam.ru\">\n    <div class=\"product-logo\">\n      <img src=\"https://docker-registry.tools.myteam.ru/static/images/nexus.png?3.16.2-01\" alt=\"Product logo\"/>\n    </div>\n    <div class=\"product-id\">\n      <div class=\"product-id__line-1\">\n        <span class=\"product-name\">Nexus Repository Manager</span>\n      </div>\n      <div class=\"product-id__line-2\">\n        <span class=\"product-spec\">OSS 3.16.2-01</span>\n      </div>\n    </div>\n  </a>\n</div>\n\n<div class=\"nexus-body\">\n  <div class=\"content-header\">\n    <img src=\"https://docker-registry.tools.myteam.ru/static/rapture/resources/icons/x32/exclamation.png?3.16.2-01\" alt=\"Exclamation point\" aria-role=\"presentation\"/>\n    <span class=\"title\">Error 404</span>\n    <span class=\"description\">Not Found</span>\n  </div>\n  <div class=\"content-body\">\n    <div class=\"content-section\">\n      Not Found\n    </div>\n      </div>\n</div>\n</body>\n</html>\n\n"
x Failed to start: failed to pull Selenoid image

```

**Comment by patsevanton** [comment]
Error
```
docker pull docker-registry.tools.myteam.ru/aerokube/selenoid:1.9.2
Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>404 - Nexus Repository Manager</title>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n\n\n  <!--[if lt IE 9]>\n  <script>(new Image).src=\"https://docker-registry.tools.myteam.ru/favicon.ico?3.16.2-01\"</script>\n  <![endif]-->\n  <link rel=\"icon\" type=\"image/png\" href=\"https://docker-registry.tools.myteam.ru/favicon-32x32.png?3.16.2-01\" sizes=\"32x32\">\n  <link rel=\"mask-icon\" href=\"https://docker-registry.tools.myteam.ru/safari-pinned-tab.svg?3.16.2-01\" color=\"#5bbad5\">\n  <link rel=\"icon\" type=\"image/png\" href=\"https://docker-registry.tools.myteam.ru/favicon-16x16.png?3.16.2-01\" sizes=\"16x16\">\n  <link rel=\"shortcut icon\" href=\"https://docker-registry.tools.myteam.ru/favicon.ico?3.16.2-01\">\n  <meta name=\"msapplication-TileImage\" content=\"https://docker-registry.tools.myteam.ru/mstile-144x144.png?3.16.2-01\">\n  <meta name=\"msapplication-TileColor\" content=\"#00a300\">\n\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://docker-registry.tools.myteam.ru/static/css/nexus-content.css?3.16.2-01\"/>\n</head>\n<body>\n<div class=\"nexus-header\">\n  <a href=\"https://docker-registry.tools.myteam.ru\">\n    <div class=\"product-logo\">\n      <img src=\"https://docker-registry.tools.myteam.ru/static/images/nexus.png?3.16.2-01\" alt=\"Product logo\"/>\n    </div>\n    <div class=\"product-id\">\n      <div class=\"product-id__line-1\">\n        <span class=\"product-name\">Nexus Repository Manager</span>\n      </div>\n      <div class=\"product-id__line-2\">\n        <span class=\"product-spec\">OSS 3.16.2-01</span>\n      </div>\n    </div>\n  </a>\n</div>\n\n<div class=\"nexus-body\">\n  <div class=\"content-header\">\n    <img src=\"https://docker-registry.tools.myteam.ru/static/rapture/resources/icons/x32/exclamation.png?3.16.2-01\" alt=\"Exclamation point\" aria-role=\"presentation\"/>\n    <span class=\"title\">Error 404</span>\n    <span class=\"description\">Not Found</span>\n  </div>\n  <div class=\"content-body\">\n    <div class=\"content-section\">\n      Not Found\n    </div>\n      </div>\n</div>\n</body>\n</html>\n\n"
```

But
```
docker pull docker-registry.tools.myteam.ru:10443/aerokube/selenoid:1.9.2
1.9.2: Pulling from aerokube/selenoid
Digest: sha256:fb3c9d417a5ffc05fc61e1931b78e1cf823db28da05b3f313c72014bbd5cce9b
Status: Image is up to date for docker-registry.tools.myteam.ru:10443/aerokube/selenoid:1.9.2
```

**Comment by patsevanton** [comment]
May be close this issue and open new issue with name "cm with option --registry don`t use port of registry" ??

**Comment by vania-pooh** [comment]
This one is correct.
