### ISSUE TITLE
x Failed to start: failed to create container: Error response from daemon: Conflict. The container name "/selenoid" is already in use by container "892e26f5c429c4ebd61c59589309ec4f7fd3ca373afd8464681159f277691d79". You have to remove (or rename) that container to be able to reuse that name.

### ISSUE THREAD

**Issue by wolf002** [aerokube/cm#259]
I installed the tool and everything worked
But after rebbot 
I see

> test@ubuntu:~$ sudo ./cm selenoid start
> > Using Docker
> - Your Docker API version is 1.39
> > Selenoid is already downloaded
> > Selenoid is already configured
> > Starting Selenoid...
> x Failed to start: failed to create container: Error response from daemon: Conflict. The container name "/selenoid" is already in use by container "892e26f5c429c4ebd61c59589309ec4f7fd3ca373afd8464681159f277691d79". You have to remove (or rename) that container to be able to reuse that name.
> 
> test@ubuntu:~$ sudo docker ps -a
> CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                        PORTS                    NAMES
> 07597798abb9        aerokube/selenoid-ui:1.9.1   "/selenoid-ui --sele…"   5 days ago          Exited (255) 28 minutes ago   0.0.0.0:8080->8080/tcp   selenoid-ui
> 892e26f5c429        aerokube/selenoid:1.10.0     "/usr/bin/selenoid -…"   5 days ago          Exited (126) 28 minutes ago   0.0.0.0:4444->4444/tcp   selenoid
> 336673832c37        hello-world                  "/hello"                 5 days ago          Exited (0) 5 days ago

**Comment by vania-pooh** [comment]
@wolf002 you already have another container named `selenoid`. Just remote it with `docker rm -f selenoid` and everything will work.

**Comment by wolf002** [comment]
After rebbot every thing work fine.
test@ubuntu:~$ sudo ./cm selenoid start
[sudo] password for test: 
> Using Docker
- Your Docker API version is 1.39
> Selenoid is already downloaded
> Selenoid is already configured
> Selenoid is already running

I did not delete the image
