### ISSUE TITLE
Selenoid server not starting with desired browser version

### ISSUE THREAD

**Issue by sunnysachdeva99** [aerokube/cm#263]
HI ,

I am startin selenoid server with below command
./cm selenoid start --browsers-json browser.json 

But when I go to http://localhost:4444/status, I get below status, 

Issue:- Why selenoid not showing desired browser versions ?

{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"74.0":{},"75.0":{}},"firefox":{"67.0":{},"68.0":{}},"opera":{"58.0":{},"60.0":{}}}}

browser.json has

{
    "chrome": {
        "default": "81.0",
        "versions": {
            "80.0": {
                "image": "selenoid/chrome:80.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=512m"
                }
            },
            "81.0": {
                "image": "selenoid/chrome:81.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=512m"
                }
            }
        }
    },
    "firefox": {
        "default": "76.0",
        "versions": {
            "75.0": {
                "image": "selenoid/firefox:75.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "76.0": {
                "image": "selenoid/firefox:76.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "opera": {
        "default": "68.0",
        "versions": {
            "67.0": {
                "image": "selenoid/opera:67.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "68.0": {
                "image": "selenoid/opera:68.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}

**Comment by vania-pooh** [comment]
@sunnysachdeva99 what is your CM version? This was implemented in 1.7.0.

**Comment by sunnysachdeva99** [comment]
./cm version
Git Revision: 1.7.1
UTC Build Time: 2019-10-08_05:28:51PM

**Comment by vania-pooh** [comment]
@sunnysachdeva99 try to run `cm` with `--force` flag to overwrite any old `browsers.json` files that could exist before.

**Comment by Mypaal7** [comment]
Hi @vania-pooh 
to me also Not able to see the SELENOID with desired browsers and instead showing issue please refer to screenshot
<img width="1434" alt="Screenshot 2021-09-23 at 7 36 06 PM" src="https://user-images.githubusercontent.com/50581842/134522466-3592ef8e-5ec1-4168-b015-03406d8a1e95.png">
Can you please help

**Comment by Mypaal7** [comment]
Hi @vania-pooh Can you please help with this

**Comment by vania-pooh** [comment]
@Mypaal7 incorrect `--selenoid-uri` value.

I'm closing this.
