### ISSUE TITLE
selenoid container stops after 5 minutes automatically

### ISSUE THREAD

**Issue by dibyaranjan-pg** [aerokube/cm#264]
Is there a way to keep selenoid container running always. Right now it stops after 5mins because of this default 

`-graceful-period duration
    graceful shutdown period in time.Duration format, e.g. 300s or 500ms (default 5m0s)`

**Comment by vania-pooh** [comment]
@dibyaranjan-pg that's not true, Selenoid stops only if it receives some signal (e.g. SIGTERM or SIGKILL) from operating system. Please check what is killing Selenoid.

**Comment by dibyaranjan-pg** [comment]
@vania-pooh Yes, I got that, I am trying to find out how Selenoid is getting killed. Sorry for the confusion. Thanks for quick response.

**Comment by dibyaranjan-pg** [comment]
Not an issue, hence closing issue.
