### ISSUE TITLE
Powershell script for windows failing

### ISSUE THREAD

**Issue by vvashist9** [aerokube/cm#273]
Hi,

I am trying configure the selenoid in windows machine using the powershell command but its failing with below error message.

Powershell command : 
Invoke-Expression (New-Object System.Net.WebClient).DownloadString("https://aerokube.com/cm/posh")

Error message:
The string is missing the terminator: ".
At line:1 char:1
+ Invoke-Expression (New-Object System.Net.WebClient).DownloadString("h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by vania-pooh** [comment]
@vvashist9 this script is simply downloading a CM binary corresponding to your architecture and platform from releases page: https://github.com/aerokube/cm/releases. I would opt for completely removing this script.

**Comment by vvashist9** [comment]
Hi vania-pooh,

As suggested, i have downloaded the binary's manually. However i am still getting below error on executing "./cm.exe selenoid start --vnc"

Can you please share the complete steps?
 
Error message :

./cm.exe : The term './cm.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ./cm.exe selenoid start --vnc
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./cm.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by vania-pooh** [comment]
@vvashist9 you certainly need to run the file you downloaded. E.g. having `cm_windows_amd64.exe` correct command would be:
```
> ./cm_windows_amd64.exe selenoid start --vnc
```
Also you should change directory to the directory where this executable was actually downloaded.

**Comment by vvashist9** [comment]
@vania-pooh , Thanks... It worked.
Appreciate your support!
