### ISSUE TITLE
Hanging containers after stopping selenoid

### ISSUE THREAD

**Issue by Koilanetroc** [aerokube/cm#278]
Hi,
When I stop selenoid by `./cm selenoid stop` it doesn't stop working containers created by that selenoid. Those containers remain hanging and waiting for nothing forever.
Is it a bug or I should handle residual containers on my own?

**Comment by vania-pooh** [comment]
@Koilanetroc `cm` only start \ stop Selenoid. However currently it does this with `--force` flag and so Selenoid has no chance stop browser containers. I think we could implement `--graceful` flag that will wait for Selenoid \ Selenoid UI to stop correctly.
