### ISSUE TITLE
Not able to download cdtp/chrome

### ISSUE THREAD

**Issue by saikrishna321** [aerokube/cm#281]
@vania-pooh As per the documentation on images I'm trying to pull cdtp/chrome:86.0 as my tests use CDP.

Error:

./cm selenoid configure --browsers cdtp/chrome:84.0 -f

> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.0
> Configuring Selenoid...
x Unsupported browser: cdtp/chrome

Can you please help me?

**Comment by vania-pooh** [comment]
@saikrishna321 these images are currently not compatible with Selenoid.

**Comment by saikrishna321** [comment]
Thanks! Whats the purpose of the image if cant be used with selenoid?

**Comment by vania-pooh** [comment]
@saikrishna321 it can be [used](https://aerokube.com/moon/latest/#_accessing_chrome_developer_tools) with Moon.

**Comment by saikrishna321** [comment]
@vania-pooh Thanks! Closing this ticket
