### ISSUE TITLE
-log-output-dir is not workin

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/cm#287]
Hi,
I am using 
`./cm selenoid -g "-log-output-dir /myapps/selenoid/logs" and in config.js 

enableLog: true, 
 logName="sample.log"

I did not see any logs in  /myapps/selenoid/logs

tried without any -log-output-dir param, I did not see any log in ~/.aerokube/selenoid/logs

am I missing something?

Thanks

**Comment by vania-pooh** [comment]
@mnjagadeesh "This is a feature, not a bug". This flag is hard-coded to CM. If you wish to override it - don't use CM.

**Comment by mnjagadeesh** [comment]
@vania-pooh Thanks for this info.
