### ISSUE TITLE
Windows 10. Video is not recorded when Docker Uses the WSL 2 based engine

### ISSUE THREAD

**Issue by SergeyShidlovsky** [aerokube/cm#293]
**Precondition**
  - Install Docker on Windows 10 OS
  - Consider that docker is usign WSL 2 Based Engine
  - ![Screenshot_485](https://user-images.githubusercontent.com/24611214/109113776-725bce00-7745-11eb-8458-cf2f8c3bcb14.png)
 - Install Configuration manager
 - Install Selenoid and selenoid-UI
 - Pull videorecorder
 - 
**Steps to reproduce**
 - Run test in selenod
 - Consider that videorecorder image is in use
 - ![Screenshot_478](https://user-images.githubusercontent.com/24611214/109114183-f57d2400-7745-11eb-895b-8e58e05cf079.png)
 - After test is finished please go to folder with video and check weather video is recorded and saved

**Expected result**
 - Video is recorded and saved in video folder

**Actual result**
 - Video is not recorded and saved

**Workaround**
 - Please use Hyper-V based engine for docker
 - ![Screenshot_475](https://user-images.githubusercontent.com/24611214/109114562-7f2cf180-7746-11eb-98e3-bca18c50840e.png)

**Comment by vania-pooh** [comment]
Seems to be a CM bug. Will investigate.

**Comment by SergeyShidlovsky** [comment]
@vania-pooh Any updates with this bug?

**Comment by benzman81** [comment]
Just moved from vagrant and virtualbox to WSL 2. Same error.

**Comment by vania-pooh** [comment]
We plan to completely deprecate this tool and move to raw Docker commands instead. Too many weird cases to cover.

**Comment by benzman81** [comment]
@vania-pooh ok, thanks. We now moved to plain docker and videos work as expected.

**Comment by SergeyShidlovsky** [comment]
@vania-pooh … are you talking about deprecation of Selenoid Configuration Manager Tool?

**Comment by vania-pooh** [comment]
@SergeyShidlovsky we are considering this.

**Comment by Lucifar2** [comment]
@benzman81 Hi, could you help me to setup selenoid with Rancher desktop. Currently I am facing issue for selenoid container being in Restarting status. Do you know if you faced this same issue ?

**Comment by benzman81** [comment]
> @benzman81 Hi, could you help me to setup selenoid with Rancher desktop. Currently I am facing issue for selenoid container being in Restarting status. Do you know if you faced this same issue ?

I can share parts of our start script we use for rancher desktop in wsl. Maybe that helps:

```
#!/bin/bash

windowsUserFolder=$(wslpath "$(wslvar USERPROFILE)")
aerokubeFolder=$windowsUserFolder/.aerokube
mkdir -p $aerokubeFolder || true
mkdir -p $aerokubeFolder/selenoid || true
mkdir -p $aerokubeFolder/selenoid/config || true
mkdir -p $aerokubeFolder/selenoid/video || true
mkdir -p $aerokubeFolder/selenoid/logs || true
mkdir -p $aerokubeFolder/selenoid-ui || true

docker rm -f selenoid || true
docker rm -f selenoid-ui || true
find $aerokubeFolder/selenoid/video -mindepth 1 -maxdepth 1 -mmin +120 -name '*.mp4' | xargs rm -rf || true
find $aerokubeFolder/selenoid/logs -mindepth 1 -maxdepth 1 -mmin +120 -name '*.log' | xargs rm -rf || true

cd /home/$USER

cd /home/$USER/selenium-grid-ggr-dockerselenoid

rm $aerokubeFolder/selenoid/config/browsers.json || true

cp /YOUR_PATH_TO_BROWSERS_JSON/browsers.json $aerokubeFolder/selenoid/config/browsers.json

cat $aerokubeFolder/selenoid/config/browsers.json | /home/$USER/jq 'map(.versions)|.[]|map(.image)|.[]' | xargs -L1 docker pull

docker pull selenoid/video-recorder:latest-release

cd /home/$USER

docker run -d --name selenoid --restart=always -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v $aerokubeFolder/selenoid/config/:/etc/selenoid/:ro \
-v $aerokubeFolder/selenoid/video/:/opt/selenoid/video/ \
-v $aerokubeFolder/selenoid/logs/:/opt/selenoid/logs/ \
-e OVERRIDE_VIDEO_OUTPUT_DIR=$aerokubeFolder/selenoid/video/ \
aerokube/selenoid:1.11.0 \
-limit 2 -cpu 1.0 -mem 1g -retry-count 10 -capture-driver-logs -timeout 300s -service-startup-timeout 300s -session-attempt-timeout 300s -session-delete-timeout 300s -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -video-recorder-image selenoid/video-recorder:latest-release -log-output-dir /opt/selenoid/logs/

DOCKER_GATEWAY_ADDR=`docker inspect selenoid -f {{.NetworkSettings.Gateway}}`
docker run -d --name selenoid-ui --restart=always -p 8086:8080 aerokube/selenoid-ui:1.10.10 --selenoid-uri http://${DOCKER_GATEWAY_ADDR}:4444
```
