### ISSUE TITLE
Cant start selenoid when --browsers-json passing as argument 

### ISSUE THREAD

**Issue by MisterLight** [aerokube/cm#295]
It seems --browser-json flag isnt working: 

./cm selenoid start  --force --browsers-json "./browsers.json"
> Using Docker
- Your Docker API version is 1.41
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.3
> Configuring Selenoid...
> Requested to sync configuration from "./browsers.json"...
- Pulling image selenoid/chrome:89.0
- Pulling image selenoid/chrome:90.0
- Pulling image selenoid/firefox:86.0
- Pulling image selenoid/firefox:87.0
- Pulling image selenoid/opera:74.0
- Pulling image selenoid/opera:75.0
> Pulling video recorder image...
- Pulling image selenoid/video-recorder:latest-release
x Failed to start: open /Users/kaio/.aerokube/selenoid/browsers.json: no such file or directory

As I think it supposed that cm create the default folder (aerokube/selenoid) first and then copy the content from target json to the one that it using.  Problem its doesnt creating the default folder.  If I created it manually before run the command then works.

I also try to run "./cm selenoid start --config-dir "/test" --force --browsers-json "./browsers.json", using config dir flag but is still giving me the same error

> Using Docker
- Your Docker API version is 1.41
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.3
> Configuring Selenoid...
> Requested to sync configuration from "./browsers.json"...
- Pulling image selenoid/chrome:89.0
- Pulling image selenoid/chrome:90.0
- Pulling image selenoid/firefox:86.0
- Pulling image selenoid/firefox:87.0
- Pulling image selenoid/opera:74.0
- Pulling image selenoid/opera:75.0
> Pulling video recorder image...
- Pulling image selenoid/video-recorder:latest-release
x Failed to start: open /test/browsers.json: no such file or directory

**Comment by vania-pooh** [comment]
You are right.
