### ISSUE TITLE
How to increase "limit" parameter without restarting selenoid?

### ISSUE THREAD

**Issue by Pavel077** [aerokube/cm#297]
Hello.

We are starting selenoid via systemd, the unit file contains this start string:
`ExecStart=/root/selenoid/cm_linux_amd64 selenoid start --vnc --args "-limit 10 -max-timeout 8000h"`

Is it possible to increase the total number of parallel sessions (`limit 10`) parameter without restarting the service and selenoid container with it?

**Comment by vania-pooh** [comment]
@Pavel077 no, this is not possible. We are using Golang channels to for this functionality and using channels with variable size is complicated and error prone.

**Comment by Pavel077** [comment]
Ok, thank you!
