### ISSUE TITLE
File cm_windows_386.exe blocked by antivirus

### ISSUE THREAD

**Issue by nakov** [aerokube/cm#300]
The file `cm_windows_386.exe` (Selenoid Configuration Manager for Windows) is blocked by Windows Defender:
https://github.com/aerokube/cm/releases/download/1.8.1/cm_windows_386.exe

Steps to reproduce:

1) Open https://github.com/aerokube/cm/releases/tag/1.8.1 (I am using Chrome for Windows 10)
2) Download the 32-bit version of Selenoid CM: https://github.com/aerokube/cm/releases/download/1.8.1/cm_windows_386.exe
3) The downloaded file will be completely blocked by Windows Defender antivirus:

![image](https://user-images.githubusercontent.com/1689586/125745880-610c2835-9ae4-45c9-8ad2-ea9a36c7e4c5.png)

![image](https://user-images.githubusercontent.com/1689586/125746057-0c1ee406-2374-4cdc-b7a1-17edee2e67ab.png)

![image](https://user-images.githubusercontent.com/1689586/125746158-7f9623e6-c3bf-4b9f-85ba-8e214e510278.png)

**Comment by vania-pooh** [comment]
@nakov you can either build from source code or run Selenoid manually using `docker run` command.

**Comment by nakov** [comment]
> @nakov you can either build from source code or run Selenoid manually using `docker run` command.

Yes, I agree, but I think that the official release should be fixed, as well. The 64-bit version works correctly.

**Comment by vania-pooh** [comment]
@nakov what kind of fix would you suggest? We are building all binaries on Github Actions using official Go compiler.

**Comment by nakov** [comment]
I think the file can be submitted to Microsoft antivirus database as false positive here:
https://www.microsoft.com/en-us/wdsi/filesubmission

I tried to submit it, but the submission service responded "File upload failed - please try again."
