### ISSUE TITLE
Unable to configure/update safari (WebKitGTK)

### ISSUE THREAD

**Issue by lorsatti** [aerokube/cm#302]
`$ ./cm selenoid update --browsers safari:14.0`

Expected to pull `browsers/safari:14.0`, similarly to 

`$ ./cm selenoid update --browsers MicrosoftEdge:93.0`
which pulls `browsers/edge:93.0`

**Comment by vania-pooh** [comment]
Currently this is not supported as Safari images are considered experimental.
