### ISSUE TITLE
Ability to mount a volume

### ISSUE THREAD

**Issue by lorsatti** [aerokube/cm#303]
### New Feature: Mount a Volume
Like `./cm selenoid update --volumes ["/mnt/share:/home/selenium/Uploads:ro"]`, translating to a volume section for each browser version in `browsers.json`:
```json
"volumes": [
  "/mnt/share:/home/selenium/Uploads:ro"
]
```

### Use Case
It would be useful while testing browser extensions, or if a file for fake audio capture is needed in the container.
Example with `ChromeOptions`:
```java
ChromeOptions options() {
    ChromeOptions opt = new ChromeOptions();
    //set path of extension directory
    opt.addArguments("load-extension=/home/selenium/Uploads/MyExtension_v0.1.2");
    //set path of .wav file for fake audio capture
    opt.addArguments("use-file-for-fake-audio-capture=/home/selenium/Uploads/speaker.wav");
    //...
    return opt;
}
```

**Comment by vania-pooh** [comment]
We consider `cm` a tool for quick installation with reasonable default settings suitable for 90% of cases. Using volumes is an advanced feature and is always available by editing `browsers.json` file. So saving this as a feature request but not sure when this is going to be implemented.
