### ISSUE TITLE
How to use Selenoid server remotely

### ISSUE THREAD

**Issue by riraga001m** [aerokube/cm#319]
Hi I have setup the selenoid hub using docker in one one of the VM, 
I am able to access webpage via http://ip:8080 from other machines too
If I use to run automation from other machine using ip:4444 or ip:8080, I get no webdriver error.

![image](https://user-images.githubusercontent.com/93780328/184237336-40ab54d8-80c5-4856-9bdf-7a11918940c5.png)

Instead of this localhost I am using IP of this VM from other machines.

Am I missing something? the ports are open to access from other machine.

Help is much appreciated, Thanks in advance,

PS: java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.

**Comment by vania-pooh** [comment]
@riraga001m this is Selenide exception, so far as I can remember. You need to configure Selenide to work with Selenoid. There is a plugin for that.

**Comment by riraga001m** [comment]
@vania-pooh
seems Docker needed a restart, after the server reboot, I could use the VM selenoid webdriver from my local laptop, VMip:4444
But same if I use in Jenkins I see same issue, Please suggest if Jenkins need any extra plugin.

Thanks for the help.

**Comment by vania-pooh** [comment]
@riraga001m Selenium is HTTP-based software, you don't need any additional plugins to use it.

**Comment by riraga001m** [comment]
It worked fine. It was connectivity issue between hosted server and Jenkins server.
