### ISSUE TITLE
new machine breaking Chrome 

### ISSUE THREAD

**Issue by struga0258** [aerokube/cm#320]
I recently reinstalled all my test code in a new machine and also pulled new Solenoid config manager, when I did this and ran it chrome was not responding. After comparing my browser.json i noticed that in my old one I had this line `"--whitelisted-ips=",` but in the new code this was missing. When adding this it fixed all my issues. Does anyone know why this line is needed?

**Comment by vania-pooh** [comment]
@struga0258 are you using Selenoid with Docker? This flag allows access to Chromedriver from hosts other than localhost.

**Comment by struga0258** [comment]
The command i use is `selenoid_windows_amd64.exe -disable-docker -conf %HOMEPATH%\.aerokube\selenoid\browsers.json`, i usually just run on localhost but without that command local host also didnt work.
