### ISSUE TITLE
Question about settings

### ISSUE THREAD

**Issue by elvovsky** [aerokube/cm#321]
I have selenoid running on windows with docker. What I am looking for and I don't seem to be able to find the info is how do I determine what the options are that this was started with. When I issue "cm selenoid status" command, the output shows me that it is running the different version than what I see running in docker, it also shows me that the config directory is the directory that does not exist and it is not configured. So how do I determine what it is actually using as the config in the docker.
When i look at the docker log , it shows me linux path.  Am I correct in assuming that cm only needs to be run once to set the config and then the configuration is set in docker?
If I look at the full command of docker it also only shows the conf directory as /etc/selenoid/browsers.json, however I am not sure if there is a mapping between that path and local windows path
I did look at the online docs, but did not seem to find it. I do see a lot of examples setting the options. 
I am sorry if this was already asked and answered, in which case just point me to it. Any help would be appreciated

**Comment by vania-pooh** [comment]
@elvovsky you can simply issue `docker inspect selenoid` to view Selenoid container status as JSON.

**Comment by elvovsky** [comment]
Thank You Ivan @vania-pooh! I can see mounts there.  I am good. However, just to confirm "cm" is just a friendlier way to create a config that docker would run? Since  the output of the cm solenoid status is not correct

**Comment by vania-pooh** [comment]
@elvovsky as any software CM can have bugs, especially under Windows where things are changing fast.

**Comment by elvovsky** [comment]
Ivan @vania-pooh , I understand. Quick question , is there a document that talks about controlling versions of docker selenoid containers via cm , since there is no "specific" dockerfile . For example, how do I upgrade the version of selenoid container running . Is that a parameter to cm or does it have to be done at the docker level ?

**Comment by vania-pooh** [comment]
@elvovsky `cm` has `--version` flag for that.
