### ISSUE TITLE
Docker Rootless (not  supported)

### ISSUE THREAD

**Issue by niklasschaeffer** [aerokube/cm#329]
Hi,
currently there is no way to tell CM to start docker containers as user in Linux. Basically you have to symlink the docker.sock from the home directory path to the unix run path like so:

```
ln -s ~/.docker/desktop/docker.sock /var/run/docker.sock
```

Is there a way we could get this to work with a user install ?

**Comment by niklasschaeffer** [comment]
nah you are missing the point. if you install docker desktop for linux you can simply only install it inside user directory. there is no file /var/run/docker.sock existent.

**Comment by vania-pooh** [comment]
@niklasschaeffer we never tested such scenario but CM relies on standard Docker client and so variables like `DOCKER_HOST` and other ones will work. https://docs.docker.com/engine/reference/commandline/cli/#environment-variables

**Comment by niklasschaeffer** [comment]
@vania-pooh you were right DOCKER_HOST does work indeed :) thanks
