### ISSUE TITLE
Mac M1 - when starting cm (1.8.4), can not access Docker

### ISSUE THREAD

**Issue by mcmpdude** [aerokube/cm#331]
When startin cm_darwin_arm64 (1.8.4) on MacOS 13.3.1. with docker (4.17.0) installed i get the following error:

`Failed to initialize: [can not access Docker: make sure you have Docker installed and current user has access permissions]`
i can access docker and start images etc. Not sure if this is an M1 bug?

i also tried with the `curl -s https://aerokube.com/cm/bash` command. Same problem occures.

**Comment by vania-pooh** [comment]
@mcmpdude make sure you can run `docker ps` from the same user you are using to run `cm`.

**Comment by yj0930** [comment]
I have the same issue. And I'm sure the "docker ps" command can be running by the same user normally.

**Comment by vania-pooh** [comment]
@yj0930 are you running `cm` with sudo?

**Comment by yj0930** [comment]
No.
I just refer [this](https://stackoverflow.com/questions/72557053/why-does-colima-failed-to-find-docker-daemon) and the issue was resolved.
