### ISSUE TITLE
Configuring Selenoid via CM with Video-Recording possible?

### ISSUE THREAD

**Issue by arivictor** [aerokube/cm#333]
Hi there,

I'm reading the documentation on CM and it's all pretty straight forward and I can get it setup and running. However I want to include video recording container along side it but the documentation shows starting Selenoid directly from docker. This is fine, I can do that, but it just means I'll reconfigure my deployment to use docker directly for Selenoid and Selenoid-UI instead of CM. So I was just wondering if I can get the setup complete from CM alone?

**Comment by arivictor** [comment]
Read the docs a little harder.

> All these actions are automatically done when starting Selenoid via [Configuration Manager](http://aerokube.com/cm/latest/) selenoid start command.

**Comment by vania-pooh** [comment]
@arivictor yep, CM does default Selenoid configuration suitable for the majority of standard use cases.
