### ISSUE TITLE
Failed to initialize: [can not access Docker: make sure you have Docker installed and current user has access permissions]

### ISSUE THREAD

**Issue by Rabindra184** [aerokube/cm#339]
I am not able to start run the command in Mac M1 as I am getting this error.

Command:  ./cm_darwin_amd64 selenoid start --vnc

Error:

Failed to initialize: [can not access Docker: make sure you have Docker installed and current user has access permissions]

**Comment by vania-pooh** [comment]
Duplicate of https://github.com/aerokube/cm/issues/331.
