### ISSUE TITLE
CM may start selenoid container in different network than one of the browser containers 

### ISSUE THREAD

**Issue by matez0** [aerokube/cm#340]
If I see well, `cm` starts the `selenoid` container in a wired-in network *selenoid*:
https://github.com/aerokube/cm/blob/5a7f7397d554502fca0267a8224f3679bce61b4b/selenoid/docker.go#L737
https://github.com/aerokube/cm/blob/5a7f7397d554502fca0267a8224f3679bce61b4b/selenoid/docker.go#L793

But at the same time it is possible to configure a different network for the browser containers with `-container-network`:
https://github.com/aerokube/cm/blob/5a7f7397d554502fca0267a8224f3679bce61b4b/selenoid/docker.go#L779

How can the `selenoid` container work together with a browser container, if they are not in the same docker network?

Why the network of the `selenoid` container is not configurable?

**Comment by vania-pooh** [comment]
@matez0 cm is a tool that just launches a Docker container with Selenoid in automated way and settings that are suitable for the majority of use cases. You can deliver the same installation manually with Docker Compose and a shell script. This is why network name is hard-coded. We don't have plans to make this configurable in CM.

**Comment by matez0** [comment]
Even if the docker network is not planned to be configurable, the selenoid network should be set to the value given in the `-container-network` to have a usable system.
This would take not much effort to fix, would not?

**Comment by vania-pooh** [comment]
@matez0 yes, that should be doable.
