### ISSUE TITLE
No htpasswd possible

### ISSUE THREAD

**Issue by niklasschaeffer** [aerokube/cm#353]
Hello,
right now there is no possible way to use a generated htpasswd with the selenoid-ui start command. Would it be possible to add this ? Or is there a way i just don't know about to get this to work.

**Comment by vania-pooh** [comment]
We consider this an advanced option and CM was created to automate basic scenarios. So I don't think we'll implement such feature in next releases.

**Comment by niklasschaeffer** [comment]
Well for me Restricting Access to a publicly available Webserver is Not an "advanced Option" especially when there is no Option for enabling that in Selenoid itself but okay.
