### ISSUE TITLE
Failed to pull image: Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by rekby** [aerokube/cm#57]
OS: Centos 7 minimal + docker 
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

./cm_1.0.0 selenoid download # - I have json with browsers.

All newer versions fails with error:
Failed to pull image "aerokube/selenoid:latest-release": Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)

[root@localhost ~]# ./cm_1.1.0 selenoid download
2017/07/19 07:58:22 Using Docker...
2017/07/19 07:58:22 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 07:58:24 Failed to list images: Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)
2017/07/19 07:58:24 Downloading Selenoid...
2017/07/19 07:58:24 Fetching tags for image "aerokube/selenoid"...
2017/07/19 07:58:24 registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
2017/07/19 07:58:26 Failed to pull image "aerokube/selenoid:latest-release": Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)
2017/07/19 07:58:26 Failed to download Selenoid release: failed to pull Selenoid image

[root@localhost ~]# ./cm_1.2.1 selenoid download
2017/07/19 07:59:12 Using Docker...
2017/07/19 07:59:12 registry.ping url=https://registry.hub.docker.com/v2/
2017/07/19 07:59:15 Failed to list images: Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)
2017/07/19 07:59:15 Downloading Selenoid...
2017/07/19 07:59:15 Fetching tags for image "aerokube/selenoid"...
2017/07/19 07:59:15 registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
2017/07/19 07:59:16 Failed to pull image "aerokube/selenoid:latest-release": Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)
2017/07/19 07:59:16 Failed to download: failed to pull Selenoid image

**Comment by aandryashin** [comment]
Please specify docker api version using environment variable like the
following:

$ DOCKER_API_VERSION=1.24 ./cm selenoid start

2017-07-19 7:32 GMT+03:00 Timofey Koolin <notifications@github.com>:

**Comment by rekby** [comment]
Thanks for workaround

**Comment by rekby** [comment]
Can you set env var internally - from cm. For binary work fine with docker api right after download?

**Comment by vania-pooh** [comment]
@rekby I don't get the question but we are using the latest Docker client which by default expects Docker API 1.29. So setting environment variable is the expected way of overriding this setting. Docker client works in the same way.

**Comment by vania-pooh** [comment]
Nothing more to do here. Closing.
