### ISSUE TITLE
limit is not configurable

### ISSUE THREAD

**Issue by RouR** [aerokube/cm#64]
The command

>  ./cm selenoid start --args "-limit 10"

 from docs http://aerokube.com/cm/latest/ is not work. (Error: unknown flag: --args)

The command

> ./cm selenoid configure [--limit 2]

is not work (Nothing changed, limit is still 5)

Please, fix it

**Comment by lanwen** [comment]
Please add your cm version

**Comment by RouR** [comment]
./cm version
Git Revision: 0ed552db269575e2a7037bceda150479b6ca7c7f
UTC Build Time: 2017-06-21_10:23:05AM

**Comment by lanwen** [comment]
As you can see - your version is not latest. Even not latest-release. Please upgrade

**Comment by RouR** [comment]
I used the instructions from http://aerokube.com/selenoid/latest/ 

> curl -L -o cm https://github.com/aerokube/cm/releases/download/1.1.2/cm_linux_amd64

It will be good update the links to latest version.

Anyway, after upgrade

> ./cm version
> Git Revision: 1.2.1
> UTC Build Time: 2017-07-17_09:51:06AM

I have try:

> ./cm selenoid stop
> ./cm selenoid start --args "-limit 1"

It's work (stop is important, and it's not described in docs)

> ./cm selenoid configure [--limit 2]
> ./cm selenoid configure -f [--limit 3]

It's not work

**Comment by vania-pooh** [comment]
1) You can use `--force` flag instead of `stop`.
2) `--limit` flag was removed from `cm` in version 1.2.0 in favor to `--args`. Updated `cm` version in Selenoid docs: https://github.com/aerokube/selenoid/pull/175.
