### ISSUE TITLE
Selenoid under Windows Docker Toolbox still fails to start

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/cm#70]
[inspect040817.txt](https://github.com/aerokube/cm/files/1202236/inspect040817.txt)
```
2017/08/04 19:17:29 new docker client: could not read CA certificate "C:\\Users\\admin\\.docker\\machine\\machines\\default/ca.pem": open C:\Users\admin\.docker\machine\machines\default/ca.pem: no such file or directory
```

**Comment by vania-pooh** [comment]
Need to try to reproduce with latest DockerToolbox for Windows. Seems to be Docker issue with paths.

**Comment by ollyjohn** [comment]
Has there been any progress on this?  I've been trying to set it up on a Windows machine but haven't had any luck as it doesn't seem to like using the /etc directory (rightly so)

**Comment by vania-pooh** [comment]
@ollyjohn unfortunately can't find Windows computer to reproduce. Could you provide more details - what's not working?

**Comment by ollyjohn** [comment]
Ah, was a false alarm, I'd misconfigured something in my test config so it wasn't calling the right URL for the selenium hub.

**Comment by vania-pooh** [comment]
Closing because Docker Toolbox is too old and deprecated. Not supporting it in newer CM versions.
