### ISSUE TITLE
Selenoid can not start with aruments --args

### ISSUE THREAD

**Issue by MissiaL** [aerokube/cm#76]
If i start selenoid with command
`C:\selenoid>cm_windows_amd64.exe selenoid start --args "--limit 10"`
I get errors:
`017/08/26 10:50:09 C:\Users\petrm\.aerokube\selenoid\selenoid_windows_amd64.exe: browsers config: read error: open config/browsers.json: The system cannot find the path specified.`

**Comment by vania-pooh** [comment]
This is because `--args` overrides all args including `-conf`. With `--args` you need to specify all args and not only ones you want to override. When implementing this I thought that otherwise it would not be transparent which args are automatically assigned and which come from `--args`.

**Comment by MissiaL** [comment]
Okay, thx)
