### ISSUE TITLE
docker.sock for Windows support 

### ISSUE THREAD

**Issue by unickq** [aerokube/cm#85]
Add ability to mount **docker.sock** for Windows with double slashes:

`-v //var/run/docker.sock:/var/run/docker.sock`

Works with _Docker for Windows 17.06_.
Validated with already configured browsers.json
`docker run --rm -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v "%dir_with_selenoidConfig%:/etc/selenoid" aerokube/selenoid:latest-release start`

**Comment by vania-pooh** [comment]
This is related to #81.

**Comment by vania-pooh** [comment]
Duplicate of #117.
