### ISSUE TITLE
Change Selenoid Port

### ISSUE THREAD

**Issue by ryan-levell-twc** [aerokube/cm#88]
I am trying to use Selenoid + Ggr, but both run on port 4444 by default. Is it possible to change the port of Selenoid via `./cm selenoid start`? I don't see it in the flags:
```
Flags:
  -a, --architecture string       target architecture (drivers only) (default "amd64")
  -g, --args string               additional service arguments (e.g. "-limit 5")
  -w, --browser-env string        override container or driver environment variables (e.g. "KEY1=value1 KEY2=value2")
  -b, --browsers string           comma separated list of browser names to process
  -j, --browsers-json string      browsers JSON data URL (in most cases never need to be set manually) (default "https://raw.githubusercontent.com/aerokube/cm/master/browsers.json")
  -c, --config-dir string         directory to save files (default "/home/ubuntu/.aerokube/selenoid")
  -e, --env string                override service environment variables (e.g. "KEY1=value1 KEY2=value2")
  -f, --force                     force action
  -l, --last-versions int         process only last N versions (Docker only) (default 2)
  -n, --no-download               only output config file without downloading images or drivers
  -o, --operating-system string   target operating system (drivers only) (default "linux")
  -q, --quiet                     suppress output
  -r, --registry string           Docker registry to use (default "https://registry.hub.docker.com")
  -t, --tmpfs int                 add tmpfs volume sized in megabytes (Docker only)
  -v, --version string            desired version; default is latest release (default "latest")
  -s, --vnc  
```

I am using the guide at http://aerokube.com/ggr/latest/ and it uses Selenium Grid with port 4445:
`java -jar selenium-server-standalone.jar -port 4445`
I want to use the same guide with Selenoid.

**Comment by aandryashin** [comment]
Use -listen option like the following:

selenoid -listen :5555
ggr -listen :8888

if  you are starting selenoid using cm pass all options via -args:

cm selenoid start -args "-listen :4445"

Please notr in this case you have to pass all arguments needed for selenoid.

2017-11-03 23:52 GMT+03:00 rlevell <notifications@github.com>:

**Comment by ryan-levell-twc** [comment]
Your command `cm selenoid start -args "-listen :4445"` treats `-listen` as another command and not as the value for `-args`:

`Error: invalid argument "isten :4445" for listen :4445: strconv.ParseInt: parsing "isten :4445": invalid syntax`

**Comment by vania-pooh** [comment]
@ryan-levell-twc unfortunately this is not possible. What you can do instead is:
```
$ cm selenoid configure <args-if-needed...> # This does all except starting Selenoid container
$ docker run -d --name selenoid -p 4444:4444 -v ~/.aerokube/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest-release # Manually start Selenoid container and adjust ports as needed
```

**Comment by vania-pooh** [comment]
Decided to implement this. :)

**Comment by ryan-levell-twc** [comment]
Great! Thanks @vania-pooh

**Comment by vania-pooh** [comment]
@ryan-levell-twc this is implemented and available in `aerokube/cm:latest` image. To customize Selenoid port type: `./cm selenoid start --port 4445`. Please check that it works for you before we release. I can build a binary for you to test if needed - just provide your platform.

**Comment by ryan-levell-twc** [comment]
I've only ever run the binary. Is this how I run the image?
```
docker run -v /var/run/docker.sock:/var/run/docker.sock aerokube/cm:latest selenoid start --port 4445
```

**Comment by ryan-levell-twc** [comment]
Does this go for the other flags as well such as `limit`? or will that work with `-args`?

**Comment by vania-pooh** [comment]
Good. Will release this soon.

**Comment by vania-pooh** [comment]
Released in https://github.com/aerokube/cm/releases/tag/1.2.6.
